org: csdias
app: rest-api
service: aws-node-rest-api-project

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

environment:
  DYNAMODB_TEST_TABLE: ${self:custom.dynamodb.testTable}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get

custom:
  dynamodb:
    testTable: ${opt:stage, 'dev'}-test
